### ISSUE TITLE
Support for lower case and special symbols?

### ISSUE THREAD

**Issue by ichvii** [justarandomgeek/factorio-signalstrings#1]
I think the best way to do so would be to add a virtual signal for each character, that does not already have one. 

I am also aware, that the easiest way to reach, what i actually need ( the ability to "edit" a bluprint and recapture it under the same name using conman) is to comment out a line in my version of conman. The second easiest is to edit conman to have an option of not overwriting the label when capturing a blueprint. This solution is clearly the solution with the most work involved. But it would also have the most applications.

**Comment by justarandomgeek** [comment]
signalstrings provides an api for mods that create new signals to register them as characters. Nixie Tubes does this will all the symbols it provides.
